#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Nao_Vigil

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_Nao_Vigil.ABP_Nao_Vigil_C.AnimBlueprintGeneratedConstantData
// 0x1727 (0x1728 - 0x0001)
struct ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_765;                                // 0x0004(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_766;                               // 0x0010(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_767;                                // 0x0020(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_768;                                // 0x0028(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_769;                                // 0x0030(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_770;                                 // 0x0038(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_771;                                // 0x003C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_772;                                 // 0x0044(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_773;                                // 0x0048(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_774;                                // 0x0050(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_775;                                // 0x0058(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_776;                                 // 0x0060(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_777;                                // 0x0064(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_778;                                // 0x006C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_779;                                // 0x0074(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_780;                                // 0x007C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 __ArrayProperty_781;                               // 0x0088(0x0010)(BlueprintVisible)
	class FName                                   __NameProperty_782;                                // 0x0098(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_783;                                // 0x00A0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_784;                                // 0x00A8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_785;                                 // 0x00B0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_786;                                // 0x00B4(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_787;                                 // 0x00BC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_788;                                // 0x00C0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_789;                                 // 0x00C8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_790;                                // 0x00CC(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_791;                                 // 0x00D4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_792;                                // 0x00D8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_793;                                 // 0x00E0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_794;                                // 0x00E4(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_795;                                 // 0x00EC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_796;                                // 0x00F0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_797;                                 // 0x00F8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_798;                                // 0x00FC(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_799;                                 // 0x0104(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_800;                                // 0x0108(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_801;                               // 0x010C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_802;                              // 0x0110(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_803;                               // 0x013C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_804;                                // 0x0140(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_805;                                // 0x0141(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x2];                                      // 0x0142(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_806;                                // 0x0144(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_807;                                // 0x014C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_808;                                 // 0x0154(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_809;                                // 0x0158(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_810;                                 // 0x0160(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_811;                                // 0x0164(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_812;                                // 0x016C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_813;                                 // 0x0174(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendProfile*                          __BlendProfile_814;                                // 0x0178(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_815;                                  // 0x0180(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_816;                                // 0x0188(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_817;                                // 0x0189(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_818;                                // 0x018A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18B[0x5];                                      // 0x018B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_819;                               // 0x0190(0x0010)(BlueprintVisible, EditFixedSize)
	struct FAnimNodeFunctionRef                   __StructProperty_820;                              // 0x01A0(0x0020)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x01C0(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0240(0x0018)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                                // 0x0258(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_38;                 // 0x0288(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_37;                 // 0x02B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_27;                   // 0x02E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer;                    // 0x0318(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_1;                   // 0x0348(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_23;                      // 0x0378(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_26;                   // 0x03A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_22;                      // 0x03D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_2;                      // 0x0408(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_2;                    // 0x0438(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_36;                 // 0x0468(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_35;                 // 0x0498(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_34;                 // 0x04C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_33;                 // 0x04F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_32;                 // 0x0528(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_31;                 // 0x0558(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_30;                 // 0x0588(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_29;                 // 0x05B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_28;                 // 0x05E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_27;                 // 0x0618(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_26;                 // 0x0648(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_25;                 // 0x0678(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_24;                 // 0x06A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_23;                 // 0x06D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_22;                 // 0x0708(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_21;                 // 0x0738(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_20;                 // 0x0768(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_25;                   // 0x0798(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_21;                      // 0x07C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_24;                   // 0x07F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_20;                      // 0x0828(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_23;                   // 0x0858(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_19;                      // 0x0888(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_22;                   // 0x08B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_21;                   // 0x08E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_20;                   // 0x0918(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum_2;                   // 0x0948(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_18;                      // 0x0978(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_19;                 // 0x09A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_19;                   // 0x09D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_17;                      // 0x0A08(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_18;                   // 0x0A38(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_16;                      // 0x0A68(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_18;                 // 0x0A98(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_17;                   // 0x0AC8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_15;                      // 0x0AF8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_16;                   // 0x0B28(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_14;                      // 0x0B58(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_17;                 // 0x0B88(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_15;                   // 0x0BB8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_14;                   // 0x0BE8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_13;                   // 0x0C18(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum_1;                   // 0x0C48(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_13;                      // 0x0C78(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;                   // 0x0CA8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;                   // 0x0CD8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;                   // 0x0D08(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum;                     // 0x0D38(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_12;                      // 0x0D68(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;                    // 0x0D98(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_11;                      // 0x0DC8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_1;                      // 0x0DF8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_1;                    // 0x0E28(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_16;                 // 0x0E58(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_15;                 // 0x0E88(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_14;                 // 0x0EB8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_13;                 // 0x0EE8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_12;                 // 0x0F18(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;                 // 0x0F48(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;                 // 0x0F78(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;                  // 0x0FA8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;                  // 0x0FD8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;                  // 0x1008(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;                  // 0x1038(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;                  // 0x1068(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;                  // 0x1098(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;                  // 0x10C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;                  // 0x10F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;                  // 0x1128(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;                    // 0x1158(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_10;                      // 0x1188(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;                    // 0x11B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_9;                       // 0x11E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;                    // 0x1218(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_8;                       // 0x1248(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;                    // 0x1278(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_7;                       // 0x12A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;                    // 0x12D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;                    // 0x1308(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_6;                       // 0x1338(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;                    // 0x1368(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_5;                       // 0x1398(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;                    // 0x13C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;                       // 0x13F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;                    // 0x1428(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;                       // 0x1458(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;                      // 0x1488(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;                       // 0x14B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_3;                     // 0x14E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;                       // 0x1518(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_2;                     // 0x1548(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;                         // 0x1578(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;                        // 0x15A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_2;                              // 0x15D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_1;                     // 0x1608(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose;                       // 0x1638(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_1;                              // 0x1668(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                                // 0x1698(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;                     // 0x16C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose;                      // 0x16F8(0x0030)()
};
static_assert(alignof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData) == 0x001728, "Wrong size on ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_765) == 0x000004, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_765' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __ArrayProperty_766) == 0x000010, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__ArrayProperty_766' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_767) == 0x000020, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_767' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_768) == 0x000028, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_768' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_769) == 0x000030, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_769' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_770) == 0x000038, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_770' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_771) == 0x00003C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_771' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_772) == 0x000044, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_772' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_773) == 0x000048, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_773' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_774) == 0x000050, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_774' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_775) == 0x000058, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_775' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_776) == 0x000060, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_776' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_777) == 0x000064, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_777' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_778) == 0x00006C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_778' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_779) == 0x000074, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_779' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_780) == 0x00007C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_780' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __ArrayProperty_781) == 0x000088, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__ArrayProperty_781' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_782) == 0x000098, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_782' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_783) == 0x0000A0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_783' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_784) == 0x0000A8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_784' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_785) == 0x0000B0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_785' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_786) == 0x0000B4, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_786' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_787) == 0x0000BC, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_787' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_788) == 0x0000C0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_788' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_789) == 0x0000C8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_789' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_790) == 0x0000CC, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_790' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_791) == 0x0000D4, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_791' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_792) == 0x0000D8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_792' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_793) == 0x0000E0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_793' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_794) == 0x0000E4, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_794' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_795) == 0x0000EC, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_795' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_796) == 0x0000F0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_796' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_797) == 0x0000F8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_797' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_798) == 0x0000FC, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_798' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_799) == 0x000104, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_799' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __BoolProperty_800) == 0x000108, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__BoolProperty_800' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __FloatProperty_801) == 0x00010C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__FloatProperty_801' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __StructProperty_802) == 0x000110, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__StructProperty_802' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __FloatProperty_803) == 0x00013C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__FloatProperty_803' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __EnumProperty_804) == 0x000140, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__EnumProperty_804' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __ByteProperty_805) == 0x000141, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__ByteProperty_805' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_806) == 0x000144, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_806' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_807) == 0x00014C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_807' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_808) == 0x000154, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_808' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_809) == 0x000158, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_809' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_810) == 0x000160, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_810' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_811) == 0x000164, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_811' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __NameProperty_812) == 0x00016C, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__NameProperty_812' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __IntProperty_813) == 0x000174, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__IntProperty_813' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __BlendProfile_814) == 0x000178, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__BlendProfile_814' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __CurveFloat_815) == 0x000180, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__CurveFloat_815' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __BoolProperty_816) == 0x000188, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__BoolProperty_816' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __EnumProperty_817) == 0x000189, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__EnumProperty_817' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __EnumProperty_818) == 0x00018A, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__EnumProperty_818' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __ArrayProperty_819) == 0x000190, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__ArrayProperty_819' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, __StructProperty_820) == 0x0001A0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::__StructProperty_820' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x0001C0, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000240, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root) == 0x000258, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_38) == 0x000288, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_38' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_37) == 0x0002B8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_37' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_27) == 0x0002E8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_27' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendSpacePlayer) == 0x000318, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_1) == 0x000348, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_23) == 0x000378, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_23' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_26) == 0x0003A8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_26' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_22) == 0x0003D8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_22' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine_2) == 0x000408, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SaveCachedPose_2) == 0x000438, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_36) == 0x000468, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_36' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_35) == 0x000498, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_35' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_34) == 0x0004C8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_33) == 0x0004F8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_32) == 0x000528, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_31) == 0x000558, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_30) == 0x000588, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_29) == 0x0005B8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_28) == 0x0005E8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_27) == 0x000618, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_26) == 0x000648, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_25) == 0x000678, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_24) == 0x0006A8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_23) == 0x0006D8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_22) == 0x000708, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_21) == 0x000738, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_20) == 0x000768, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_25) == 0x000798, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_25' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_21) == 0x0007C8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_21' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_24) == 0x0007F8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_24' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_20) == 0x000828, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_20' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_23) == 0x000858, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_23' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_19) == 0x000888, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_22) == 0x0008B8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_22' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_21) == 0x0008E8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_21' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_20) == 0x000918, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByEnum_2) == 0x000948, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByEnum_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_18) == 0x000978, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_19) == 0x0009A8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_19) == 0x0009D8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_17) == 0x000A08, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_18) == 0x000A38, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_16) == 0x000A68, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_18) == 0x000A98, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_17) == 0x000AC8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_15) == 0x000AF8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_16) == 0x000B28, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_14) == 0x000B58, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_17) == 0x000B88, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_15) == 0x000BB8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_14) == 0x000BE8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_13) == 0x000C18, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByEnum_1) == 0x000C48, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByEnum_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_13) == 0x000C78, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_12) == 0x000CA8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_11) == 0x000CD8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_10) == 0x000D08, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByEnum) == 0x000D38, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_12) == 0x000D68, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_9) == 0x000D98, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_11) == 0x000DC8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine_1) == 0x000DF8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SaveCachedPose_1) == 0x000E28, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_16) == 0x000E58, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_15) == 0x000E88, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_14) == 0x000EB8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_13) == 0x000EE8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_12) == 0x000F18, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_11) == 0x000F48, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_10) == 0x000F78, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_9) == 0x000FA8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_8) == 0x000FD8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_7) == 0x001008, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_6) == 0x001038, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_5) == 0x001068, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_4) == 0x001098, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_3) == 0x0010C8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_2) == 0x0010F8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_1) == 0x001128, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_8) == 0x001158, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_10) == 0x001188, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_7) == 0x0011B8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_9) == 0x0011E8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_6) == 0x001218, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_8) == 0x001248, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_5) == 0x001278, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_7) == 0x0012A8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult) == 0x0012D8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_4) == 0x001308, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_6) == 0x001338, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_3) == 0x001368, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_5) == 0x001398, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_2) == 0x0013C8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_4) == 0x0013F8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_1) == 0x001428, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_3) == 0x001458, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer) == 0x001488, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_2) == 0x0014B8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose_3) == 0x0014E8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_1) == 0x001518, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose_2) == 0x001548, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult) == 0x001578, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine) == 0x0015A8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Slot_2) == 0x0015D8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Slot_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose_1) == 0x001608, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose) == 0x001638, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Slot_1) == 0x001668, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Slot) == 0x001698, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool) == 0x0016C8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SaveCachedPose) == 0x0016F8, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SaveCachedPose' has a wrong offset!");

// ScriptStruct ABP_Nao_Vigil.ABP_Nao_Vigil_C.AnimBlueprintGeneratedMutableData
// 0x0057 (0x0058 - 0x0001)
struct ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty;                                   // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_1;                                 // 0x0010(0x0010)(BlueprintVisible, EditFixedSize)
	uint8                                         __ByteProperty_2;                                  // 0x0020(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_3;                                 // 0x0028(0x0010)(BlueprintVisible, EditFixedSize)
	uint8                                         __ByteProperty_4;                                  // 0x0038(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_5;                                 // 0x0040(0x0010)(BlueprintVisible, EditFixedSize)
	uint8                                         __ByteProperty_6;                                  // 0x0050(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_7;                                  // 0x0051(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData) == 0x000008, "Wrong alignment on ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData) == 0x000058, "Wrong size on ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __FloatProperty) == 0x000004, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__FloatProperty' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000008, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __ArrayProperty_1) == 0x000010, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__ArrayProperty_1' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __ByteProperty_2) == 0x000020, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__ByteProperty_2' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __ArrayProperty_3) == 0x000028, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__ArrayProperty_3' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __ByteProperty_4) == 0x000038, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__ByteProperty_4' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __ArrayProperty_5) == 0x000040, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__ArrayProperty_5' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __ByteProperty_6) == 0x000050, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__ByteProperty_6' has a wrong offset!");
static_assert(offsetof(ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData, __BoolProperty_7) == 0x000051, "Member 'ABP_Nao_Vigil::FAnimBlueprintGeneratedMutableData::__BoolProperty_7' has a wrong offset!");

}

