#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MatchaInventoryItemUIData

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Matcha_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MatchaInventoryItemUIData.BP_MatchaInventoryItemUIData_C
// 0x0008 (0x02E8 - 0x02E0)
class UBP_MatchaInventoryItemUIData_C final : public UMatchaInventoryItemUIData
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_MatchaInventoryItemUIData(int32 EntryPoint);
	void InteractionRendererUpdated(class AActor* Renderer);
	void OnInteractionRendererUpdated(class AActor* NewInteractionRenderer, class AActor* OldInteractionRenderer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MatchaInventoryItemUIData_C">();
	}
	static class UBP_MatchaInventoryItemUIData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MatchaInventoryItemUIData_C>();
	}
};
static_assert(alignof(UBP_MatchaInventoryItemUIData_C) == 0x000008, "Wrong alignment on UBP_MatchaInventoryItemUIData_C");
static_assert(sizeof(UBP_MatchaInventoryItemUIData_C) == 0x0002E8, "Wrong size on UBP_MatchaInventoryItemUIData_C");
static_assert(offsetof(UBP_MatchaInventoryItemUIData_C, UberGraphFrame) == 0x0002E0, "Member 'UBP_MatchaInventoryItemUIData_C::UberGraphFrame' has a wrong offset!");

}

