#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MatchaGameWorldUIData

#include "Basic.hpp"

#include "Matcha_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MatchaGameWorldUIData.BP_MatchaGameWorldUIData_C
// 0x0000 (0x03D0 - 0x03D0)
class UBP_MatchaGameWorldUIData_C final : public UMatchaGameWorldUIData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MatchaGameWorldUIData_C">();
	}
	static class UBP_MatchaGameWorldUIData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MatchaGameWorldUIData_C>();
	}
};
static_assert(alignof(UBP_MatchaGameWorldUIData_C) == 0x000008, "Wrong alignment on UBP_MatchaGameWorldUIData_C");
static_assert(sizeof(UBP_MatchaGameWorldUIData_C) == 0x0003D0, "Wrong size on UBP_MatchaGameWorldUIData_C");

}

