#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BUF_ObscuraOrbPostTP

#include "Basic.hpp"

#include "Matcha_structs.hpp"
#include "Matcha_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BUF_ObscuraOrbPostTP.BUF_ObscuraOrbPostTP_C
// 0x0008 (0x0030 - 0x0028)
class UBUF_ObscuraOrbPostTP_C final : public UMatchaCharacterBuff
{
public:
	class UClass*                                 SpeedGE;                                           // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void OnBuffApplied(class AMatchaSnapNetCharacterEntity* BuffedCharacter, EObjectRarity BuffRarity) const;
	void OnBuffRemoved(class AMatchaSnapNetCharacterEntity* BuffedCharacter, EObjectRarity BuffRarity) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BUF_ObscuraOrbPostTP_C">();
	}
	static class UBUF_ObscuraOrbPostTP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBUF_ObscuraOrbPostTP_C>();
	}
};
static_assert(alignof(UBUF_ObscuraOrbPostTP_C) == 0x000008, "Wrong alignment on UBUF_ObscuraOrbPostTP_C");
static_assert(sizeof(UBUF_ObscuraOrbPostTP_C) == 0x000030, "Wrong size on UBUF_ObscuraOrbPostTP_C");
static_assert(offsetof(UBUF_ObscuraOrbPostTP_C, SpeedGE) == 0x000028, "Member 'UBUF_ObscuraOrbPostTP_C::SpeedGE' has a wrong offset!");

}

