#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharacterEntity_Base

#include "Basic.hpp"

#include "CharacterEntity_Base_classes.hpp"
#include "CharacterEntity_Base_parameters.hpp"


namespace SDK
{

// Function CharacterEntity_Base.CharacterEntity_Base_C.Check if Tempest Projectile from Gear Already Exists
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    AlreadyMadeTempest                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharacterEntity_Base_C::Check_if_Tempest_Projectile_from_Gear_Already_Exists(bool* AlreadyMadeTempest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharacterEntity_Base_C", "Check if Tempest Projectile from Gear Already Exists");

	Params::CharacterEntity_Base_C_Check_if_Tempest_Projectile_from_Gear_Already_Exists Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AlreadyMadeTempest != nullptr)
		*AlreadyMadeTempest = Parms.AlreadyMadeTempest;
}

}

