#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Hack_Chest

#include "Basic.hpp"

#include "Matcha_structs.hpp"


namespace SDK::Params
{

// Function E_Hack_Chest.E_Hack_Chest_C.ExecuteUbergraph_E_Hack_Chest
// 0x0004 (0x0004 - 0x0000)
struct E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest) == 0x000004, "Wrong alignment on E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest");
static_assert(sizeof(E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest) == 0x000004, "Wrong size on E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest");
static_assert(offsetof(E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest, EntryPoint) == 0x000000, "Member 'E_Hack_Chest_C_ExecuteUbergraph_E_Hack_Chest::EntryPoint' has a wrong offset!");

// Function E_Hack_Chest.E_Hack_Chest_C.GetScheduledObjectiveDisplayText
// 0x0010 (0x0010 - 0x0000)
struct E_Hack_Chest_C_GetScheduledObjectiveDisplayText final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
static_assert(alignof(E_Hack_Chest_C_GetScheduledObjectiveDisplayText) == 0x000008, "Wrong alignment on E_Hack_Chest_C_GetScheduledObjectiveDisplayText");
static_assert(sizeof(E_Hack_Chest_C_GetScheduledObjectiveDisplayText) == 0x000010, "Wrong size on E_Hack_Chest_C_GetScheduledObjectiveDisplayText");
static_assert(offsetof(E_Hack_Chest_C_GetScheduledObjectiveDisplayText, ReturnValue) == 0x000000, "Member 'E_Hack_Chest_C_GetScheduledObjectiveDisplayText::ReturnValue' has a wrong offset!");

// Function E_Hack_Chest.E_Hack_Chest_C.GetScheduledObjectiveType
// 0x0001 (0x0001 - 0x0000)
struct E_Hack_Chest_C_GetScheduledObjectiveType final
{
public:
	EScheduledObjectiveType                       ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(E_Hack_Chest_C_GetScheduledObjectiveType) == 0x000001, "Wrong alignment on E_Hack_Chest_C_GetScheduledObjectiveType");
static_assert(sizeof(E_Hack_Chest_C_GetScheduledObjectiveType) == 0x000001, "Wrong size on E_Hack_Chest_C_GetScheduledObjectiveType");
static_assert(offsetof(E_Hack_Chest_C_GetScheduledObjectiveType, ReturnValue) == 0x000000, "Member 'E_Hack_Chest_C_GetScheduledObjectiveType::ReturnValue' has a wrong offset!");

}

