#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Pickup_RareHealth

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ItemPickup_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass E_Pickup_RareHealth.E_Pickup_RareHealth_C
// 0x0010 (0x03C8 - 0x03B8)
class AE_Pickup_RareHealth_C final : public ABP_ItemPickup_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_E_Pickup_RareHealth_C;              // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Sphere;                                            // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_E_Pickup_RareHealth(int32 EntryPoint);
	void HandleReset();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"E_Pickup_RareHealth_C">();
	}
	static class AE_Pickup_RareHealth_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AE_Pickup_RareHealth_C>();
	}
};
static_assert(alignof(AE_Pickup_RareHealth_C) == 0x000008, "Wrong alignment on AE_Pickup_RareHealth_C");
static_assert(sizeof(AE_Pickup_RareHealth_C) == 0x0003C8, "Wrong size on AE_Pickup_RareHealth_C");
static_assert(offsetof(AE_Pickup_RareHealth_C, UberGraphFrame_E_Pickup_RareHealth_C) == 0x0003B8, "Member 'AE_Pickup_RareHealth_C::UberGraphFrame_E_Pickup_RareHealth_C' has a wrong offset!");
static_assert(offsetof(AE_Pickup_RareHealth_C, Sphere) == 0x0003C0, "Member 'AE_Pickup_RareHealth_C::Sphere' has a wrong offset!");

}

