#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Trap_AiMi_NeutralSpecialZone

#include "Basic.hpp"

#include "E_Trap_AiMi_NeutralSpecialZone_classes.hpp"
#include "E_Trap_AiMi_NeutralSpecialZone_parameters.hpp"


namespace SDK
{

// Function E_Trap_AiMi_NeutralSpecialZone.E_Trap_AiMi_NeutralSpecialZone_C.ExecuteUbergraph_E_Trap_AiMi_NeutralSpecialZone
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AE_Trap_AiMi_NeutralSpecialZone_C::ExecuteUbergraph_E_Trap_AiMi_NeutralSpecialZone(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Trap_AiMi_NeutralSpecialZone_C", "ExecuteUbergraph_E_Trap_AiMi_NeutralSpecialZone");

	Params::E_Trap_AiMi_NeutralSpecialZone_C_ExecuteUbergraph_E_Trap_AiMi_NeutralSpecialZone Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function E_Trap_AiMi_NeutralSpecialZone.E_Trap_AiMi_NeutralSpecialZone_C.OnCharacterOverlapEnded
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AMatchaSnapNetCharacterEntity*    OverlappedCharacter                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AE_Trap_AiMi_NeutralSpecialZone_C::OnCharacterOverlapEnded(class AMatchaSnapNetCharacterEntity* OverlappedCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Trap_AiMi_NeutralSpecialZone_C", "OnCharacterOverlapEnded");

	Params::E_Trap_AiMi_NeutralSpecialZone_C_OnCharacterOverlapEnded Parms{};

	Parms.OverlappedCharacter = OverlappedCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function E_Trap_AiMi_NeutralSpecialZone.E_Trap_AiMi_NeutralSpecialZone_C.OnCharacterOverlapStarted
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AMatchaSnapNetCharacterEntity*    OverlappedCharacter                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AE_Trap_AiMi_NeutralSpecialZone_C::OnCharacterOverlapStarted(class AMatchaSnapNetCharacterEntity* OverlappedCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Trap_AiMi_NeutralSpecialZone_C", "OnCharacterOverlapStarted");

	Params::E_Trap_AiMi_NeutralSpecialZone_C_OnCharacterOverlapStarted Parms{};

	Parms.OverlappedCharacter = OverlappedCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function E_Trap_AiMi_NeutralSpecialZone.E_Trap_AiMi_NeutralSpecialZone_C.OnPeriodicEffectInterval
// (BlueprintCallable, BlueprintEvent)

void AE_Trap_AiMi_NeutralSpecialZone_C::OnPeriodicEffectInterval()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Trap_AiMi_NeutralSpecialZone_C", "OnPeriodicEffectInterval");

	UObject::ProcessEvent(Func, nullptr);
}


// Function E_Trap_AiMi_NeutralSpecialZone.E_Trap_AiMi_NeutralSpecialZone_C.OnSpawnFinished
// (Event, Protected, BlueprintEvent)

void AE_Trap_AiMi_NeutralSpecialZone_C::OnSpawnFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Trap_AiMi_NeutralSpecialZone_C", "OnSpawnFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

