#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SpeedStatMod

#include "Basic.hpp"

#include "MatchaGameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SpeedStatMod.GE_SpeedStatMod_C
// 0x0000 (0x0320 - 0x0320)
class UGE_SpeedStatMod_C final : public UMatchaGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SpeedStatMod_C">();
	}
	static class UGE_SpeedStatMod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SpeedStatMod_C>();
	}
};
static_assert(alignof(UGE_SpeedStatMod_C) == 0x000008, "Wrong alignment on UGE_SpeedStatMod_C");
static_assert(sizeof(UGE_SpeedStatMod_C) == 0x000320, "Wrong size on UGE_SpeedStatMod_C");

}

