#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lib_Audio

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "Matcha_structs.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lib_Audio.Lib_Audio_C
// 0x0000 (0x0028 - 0x0028)
class ULib_Audio_C final : public UBlueprintFunctionLibrary
{
public:
	static int32 AkEventComponentWithInstigator(class UAkAudioEvent* AkEvent, class UAkComponent* Ak_Component, class AActor* Instigator, class UObject* __WorldContext);
	static int32 AkEventLocation(class UAkAudioEvent* AkEvent, const struct FVector& Location, class AActor* Instigator, class UObject* __WorldContext);
	static int32 AkEventRenderer(class UAkAudioEvent* AkEvent, class AActor* Renderer, class UObject* __WorldContext);
	static int32 AkEventRendererWithInstigator(class UAkAudioEvent* AkEvent, class AActor* Renderer, class AActor* Instigator, class UObject* __WorldContext);
	static void AkVelocity(class UAkComponent* Ak, double VectorLengthMin, double VectorLengthMax, double DT, const struct FVector& GetPreviousLocation, int32 InterpTimeMs, class UObject* __WorldContext, struct FVector* SetPreviousLocation, double* VectorLength, double* VectorLengthClamped);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Lib_Audio_C">();
	}
	static class ULib_Audio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULib_Audio_C>();
	}
};
static_assert(alignof(ULib_Audio_C) == 0x000008, "Wrong alignment on ULib_Audio_C");
static_assert(sizeof(ULib_Audio_C) == 0x000028, "Wrong size on ULib_Audio_C");

}

