#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PE_Item_TeleportTargetToCaster

#include "Basic.hpp"

#include "PE_Item_Base_classes.hpp"
#include "Engine_structs.hpp"
#include "Matcha_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PE_Item_TeleportTargetToCaster.PE_Item_TeleportTargetToCaster_C
// 0x0010 (0x0638 - 0x0628)
class APE_Item_TeleportTargetToCaster_C final : public APE_Item_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0628(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          PlayedSound;                                       // 0x0630(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PE_Item_TeleportTargetToCaster(int32 EntryPoint);
	void OnProjectileHit(class AActor* HitActor, const struct FMatchaHitData& HitData);
	void PullTarget(const class AActor* TargetHit);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PE_Item_TeleportTargetToCaster_C">();
	}
	static class APE_Item_TeleportTargetToCaster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APE_Item_TeleportTargetToCaster_C>();
	}
};
static_assert(alignof(APE_Item_TeleportTargetToCaster_C) == 0x000008, "Wrong alignment on APE_Item_TeleportTargetToCaster_C");
static_assert(sizeof(APE_Item_TeleportTargetToCaster_C) == 0x000638, "Wrong size on APE_Item_TeleportTargetToCaster_C");
static_assert(offsetof(APE_Item_TeleportTargetToCaster_C, UberGraphFrame) == 0x000628, "Member 'APE_Item_TeleportTargetToCaster_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(APE_Item_TeleportTargetToCaster_C, PlayedSound) == 0x000630, "Member 'APE_Item_TeleportTargetToCaster_C::PlayedSound' has a wrong offset!");

}

