#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PE_Rune_NeutralSpecialEmpowered

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function PE_Rune_NeutralSpecialEmpowered.PE_Rune_NeutralSpecialEmpowered_C.ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered
// 0x0100 (0x0100 - 0x0000)
struct PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetWorldRotation_SweepHitResult;       // 0x0008(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered) == 0x000008, "Wrong alignment on PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered");
static_assert(sizeof(PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered) == 0x000100, "Wrong size on PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered");
static_assert(offsetof(PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered, EntryPoint) == 0x000000, "Member 'PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered::EntryPoint' has a wrong offset!");
static_assert(offsetof(PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered, CallFunc_K2_SetWorldRotation_SweepHitResult) == 0x000008, "Member 'PE_Rune_NeutralSpecialEmpowered_C_ExecuteUbergraph_PE_Rune_NeutralSpecialEmpowered::CallFunc_K2_SetWorldRotation_SweepHitResult' has a wrong offset!");

}

