#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: R_InteractivePickup_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Matcha_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass R_InteractivePickup_Base.R_InteractivePickup_Base_C
// 0x0008 (0x02B0 - 0x02A8)
class AR_InteractivePickup_Base_C : public AMatchaSnapNetInteractableRenderer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_R_InteractivePickup_Base(int32 EntryPoint);
	void K2_OnUpdateFromEntity(const class AMatchaSnapNetInteractiveEntity* EntityActor, float DeltaSeconds);

	struct FVector GetInteractionPromptLocation(const class AActor* InteractingRenderer) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"R_InteractivePickup_Base_C">();
	}
	static class AR_InteractivePickup_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AR_InteractivePickup_Base_C>();
	}
};
static_assert(alignof(AR_InteractivePickup_Base_C) == 0x000008, "Wrong alignment on AR_InteractivePickup_Base_C");
static_assert(sizeof(AR_InteractivePickup_Base_C) == 0x0002B0, "Wrong size on AR_InteractivePickup_Base_C");
static_assert(offsetof(AR_InteractivePickup_Base_C, UberGraphFrame) == 0x0002A8, "Member 'AR_InteractivePickup_Base_C::UberGraphFrame' has a wrong offset!");

}

