#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Minimap_TimedChest

#include "Basic.hpp"

#include "WBP_Minimap_TimedChest_classes.hpp"
#include "WBP_Minimap_TimedChest_parameters.hpp"


namespace SDK
{

// Function WBP_Minimap_TimedChest.WBP_Minimap_TimedChest_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Minimap_TimedChest_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Minimap_TimedChest_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Minimap_TimedChest.WBP_Minimap_TimedChest_C.ExecuteUbergraph_WBP_Minimap_TimedChest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Minimap_TimedChest_C::ExecuteUbergraph_WBP_Minimap_TimedChest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Minimap_TimedChest_C", "ExecuteUbergraph_WBP_Minimap_TimedChest");

	Params::WBP_Minimap_TimedChest_C_ExecuteUbergraph_WBP_Minimap_TimedChest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Minimap_TimedChest.WBP_Minimap_TimedChest_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Minimap_TimedChest_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Minimap_TimedChest_C", "PreConstruct");

	Params::WBP_Minimap_TimedChest_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Minimap_TimedChest.WBP_Minimap_TimedChest_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Minimap_TimedChest_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Minimap_TimedChest_C", "Tick");

	Params::WBP_Minimap_TimedChest_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Minimap_TimedChest.WBP_Minimap_TimedChest_C.UpdateTimer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TimerPercent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TimeRemaining                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Minimap_TimedChest_C::UpdateTimer(double TimerPercent, int32 TimeRemaining)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Minimap_TimedChest_C", "UpdateTimer");

	Params::WBP_Minimap_TimedChest_C_UpdateTimer Parms{};

	Parms.TimerPercent = TimerPercent;
	Parms.TimeRemaining = TimeRemaining;

	UObject::ProcessEvent(Func, &Parms);
}

}

