#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_KeybindEntry

#include "Basic.hpp"

#include "WBP_KeybindEntry_classes.hpp"
#include "WBP_KeybindEntry_parameters.hpp"


namespace SDK
{

// Function WBP_KeybindEntry.WBP_KeybindEntry_C.BindInputMapping
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FEnhancedActionKeyMapping        InputMapping_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference, HasGetValueTypeHash)

void UWBP_KeybindEntry_C::BindInputMapping(const struct FEnhancedActionKeyMapping& InputMapping_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "BindInputMapping");

	Params::WBP_KeybindEntry_C_BindInputMapping Parms{};

	Parms.InputMapping_0 = std::move(InputMapping_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_4_OnKeySelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// struct FInputChord                      SelectedKey                                            (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_KeybindEntry_C::BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_4_OnKeySelected__DelegateSignature(const struct FInputChord& SelectedKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_4_OnKeySelected__DelegateSignature");

	Params::WBP_KeybindEntry_C_BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_4_OnKeySelected__DelegateSignature Parms{};

	Parms.SelectedKey = std::move(SelectedKey);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_5_OnIsSelectingKeyChanged__DelegateSignature
// (BlueprintEvent)

void UWBP_KeybindEntry_C::BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_5_OnIsSelectingKeyChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "BndEvt__WBP_KeybindEntry_OdyInputKeySelector_K2Node_ComponentBoundEvent_5_OnIsSelectingKeyChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.BndEvt__WBP_KeybindEntry_ResetButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_KeybindEntry_C::BndEvt__WBP_KeybindEntry_ResetButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "BndEvt__WBP_KeybindEntry_ResetButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.ExecuteUbergraph_WBP_KeybindEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_KeybindEntry_C::ExecuteUbergraph_WBP_KeybindEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "ExecuteUbergraph_WBP_KeybindEntry");

	Params::WBP_KeybindEntry_C_ExecuteUbergraph_WBP_KeybindEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.OnEntryHoveredChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_KeybindEntry_C*              Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_KeybindEntry_C::OnEntryHoveredChanged__DelegateSignature(class UWBP_KeybindEntry_C* Widget, bool IsHovered_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "OnEntryHoveredChanged__DelegateSignature");

	Params::WBP_KeybindEntry_C_OnEntryHoveredChanged__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.IsHovered_0 = IsHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_KeybindEntry_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_KeybindEntry_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "OnMouseEnter");

	Params::WBP_KeybindEntry_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_KeybindEntry_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "OnMouseLeave");

	Params::WBP_KeybindEntry_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.ResetInputSelector
// (BlueprintCallable, BlueprintEvent)

void UWBP_KeybindEntry_C::ResetInputSelector()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "ResetInputSelector");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.ResetToDefault
// (BlueprintCallable, BlueprintEvent)

void UWBP_KeybindEntry_C::ResetToDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "ResetToDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.SetDefaultStyle
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_KeybindEntry_C::SetDefaultStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "SetDefaultStyle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.SetHoveredStyle
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_KeybindEntry_C::SetHoveredStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "SetHoveredStyle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_KeybindEntry.WBP_KeybindEntry_C.SetKeyBind
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_KeybindEntry_C::SetKeyBind(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeybindEntry_C", "SetKeyBind");

	Params::WBP_KeybindEntry_C_SetKeyBind Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}

}

