#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HealthBar

#include "Basic.hpp"

#include "WBP_HealthBar_classes.hpp"
#include "WBP_HealthBar_parameters.hpp"


namespace SDK
{

// Function WBP_HealthBar.WBP_HealthBar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_HealthBar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthBar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HealthBar.WBP_HealthBar_C.ExecuteUbergraph_WBP_HealthBar
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HealthBar_C::ExecuteUbergraph_WBP_HealthBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthBar_C", "ExecuteUbergraph_WBP_HealthBar");

	Params::WBP_HealthBar_C_ExecuteUbergraph_WBP_HealthBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HealthBar.WBP_HealthBar_C.SetHealth
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  CurrentDamage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  MaxDamage                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HealthBar_C::SetHealth(double CurrentDamage, double MaxDamage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthBar_C", "SetHealth");

	Params::WBP_HealthBar_C_SetHealth Parms{};

	Parms.CurrentDamage = CurrentDamage;
	Parms.MaxDamage = MaxDamage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HealthBar.WBP_HealthBar_C.SetHealthBarPercent
// (Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// double                                  CurrentDamage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  MaxDamage                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HealthBar_C::SetHealthBarPercent(double CurrentDamage, double MaxDamage) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealthBar_C", "SetHealthBarPercent");

	Params::WBP_HealthBar_C_SetHealthBarPercent Parms{};

	Parms.CurrentDamage = CurrentDamage;
	Parms.MaxDamage = MaxDamage;

	UObject::ProcessEvent(Func, &Parms);
}

}

